version: 2

models:
  - name: stg_commodities
    description: "Staging table for commodity data"
    columns:
      - name: date
        description: "Observation date in YYYY-MM-DD format"
      - name: closing_price
        description: "Commodity closing price with decimal precision 4.2"
      - name: symbol
        description: "Commodity Symbol" 
  - name: stg_commodities_movement
    description: "Staging table for commodity movement data"
    columns:
      - name: date
        description: "Transaction date in YYYY-MM-DD format"
      - name: symbol
        description: "Commodity Symbol"
      - name: action
        description: "Transaction Type (buy/sell)"
      - name: quantity
        description: "Amount Transacted"